name: Installer ISO build
on:
  push:
    branches:
    - 'sk'
    - 'sk-new'
jobs:
  build:
    name: Installer ISO build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      iso_file_name: ${{ steps.build_iso.outputs.iso_file_name }}
      version: ${{ steps.build_iso.outputs.version }}
      id: ${{ steps.build_iso.outputs.id }}
    steps:
      - uses: actions/checkout@v3
      - name: Change directory
        run: cd $GITHUB_WORKSPACE
      - name: Update submodules
        run: git submodule update --init --recursive
      # - name: Download Steam
      #   run: |
      #     URL="https://steamdeck-packages.steamos.cloud/archlinux-mirror/jupiter-main/os/x86_64/steam-jupiter-stable-1.0.0.79-1.3-x86_64.pkg.tar.zst"
      #     mkdir -p chimeraos/airootfs/root/packages
      #     curl -L -o chimeraos/airootfs/root/packages/steam-jupiter-stable.pkg.tar.zst $URL
      - name: Build ISO
        id: build_iso
        run: ./build-iso-docker.sh
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.build_iso.outputs.version }}_${{ steps.build_iso.outputs.id }}
          target_commitish: ${{ github.sha }}
          name: ${{ steps.build_iso.outputs.version }} (${{ steps.build_iso.outputs.id }})
          draft: false
          prerelease: true
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            output/${{ steps.build_iso.outputs.iso_file_name }}
            output/sha256sum.txt
